const chara = [
    {
      id: 1,
      name: "ハイエンキューキン王",
      scientificNameJa: "肺炎球菌",
      scientificNameEnRubi: "ストレプトコックス・ニューモニエ",    
      scientificNameEn: "<em>Streptococcus pneumoniae</em>",
      type: "グラム陽性球菌",
      taxonomy: {phylum:"<em>Bacillota</em>",class:"<em>Bacilli</em>",order:"<em>Lactobacillales</em>",family:"<em>Streptococcaceae</em>"},
      bacterialFeatures: "<b>グラム陽性双球菌</b>（diplococcus）。<ruby>Pneumococcus<rt>ニューモコックス</rt></ruby>とも呼ばれる。<b>カタラーゼ</b>陰性（連鎖状球菌の一般的性状）。<b>α溶血性</b>（<b>不完全溶血</b>）。<b>莢膜</b>を持ち、病原因子として機能。莢膜の血清型は90種以上が知られている。栄養要求性が高く、環境中では長期間生存できない。培養には血液寒天培地などのリッチな培地を用いる。通性嫌気性菌で、37℃、5%程度の二酸化炭素存在下で発育が促進される。",
      clinicalFeatures: "<b>肺炎</b>の原因菌として最多。<b>尿中抗原</b>が診断に有用である。その他、中耳炎、髄膜炎の原因菌として重要。",
      additionalInfo: "ワクチンとして、結合型ワクチンの<b>PCV</b>、莢膜多糖ワクチンの<b>PPSV23</b>がある。耐性として、ペニシリン耐性肺炎球菌（PRSP）が知られている。",
      img: "<img src='img/chara1.png'>",
      lpsn:"<a href='https://lpsn.dsmz.de/species/streptococcus-pneumoniae', target='_blank'><em>Streptococcus pneumoniae</em></a>",
      quiztag:["グラム陽性菌","グラム陽性球菌","GPC","肺炎","市中肺炎"],
      card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-01.png",
      feature:"Royal Family", law:["侵襲性肺炎球菌感染症（5類全数）", "ペニシリン耐性肺炎球菌感染症（5類定点）"],
      bsl:2,
    },
    {
      id: 2,
      name: "インフルエンザキンXV世女王",
      scientificNameJa: "インフルエンザ菌",
      scientificNameEnRubi: "ヘモフィルス・インフルエンゼ",  
      scientificNameEn: "<em>Haemophilus influenzae</em>",
      type: "グラム陰性桿菌",
      taxonomy: {phylum:"<em>Pseudomonadota</em>",class:"<em>Gammaproteobacteria</em>",order:"<em>Pasteurellales</em>",family:"<em>Pasteurellaceae</em>"},
      bacterialFeatures: "莢膜を持つ型と持たない型が存在。莢膜の血清型は、a～fの6種類で、特にb型菌（<em>Haemophilus influenzae</em> type b, <b>Hib</b>）は侵襲性インフルエンザ菌感染症（中でも髄膜炎）の原因菌として重要である。",
      clinicalFeatures: "肺炎の原因菌として、肺炎球菌に次いで多い。その他、髄膜炎、副鼻腔炎、中耳炎、COPDの増悪や気管支炎など気道感染症の原因菌。",
      additionalInfo: "小児の髄膜炎の予防としてHibワクチンが利用可能である。耐性菌として、β-ラクタマーゼ非産生アンピシリン耐性（BLNAR）が重要。感染症法上は、侵襲性インフルエンザ菌感染症（5類全数）が重要である。",
      img: "<img src='img/chara2.png'>",
      lpsn:"<a href='https://lpsn.dsmz.de/species/haemophilus-influenzae', target='_blank'><em>Haemophilus influenzae</em></a>",quiztag:["グラム陰性菌","グラム陰性桿菌","GNR","グラム陰性小桿菌","グラム陰性短桿菌"], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-02.png", feature:"Royal Family", law:["侵襲性インフルエンザ菌感染症（5類全数）"],
      bsl:2,
    },
    {
      id: 3,
      name: "マイコプラズマ姫",
      scientificNameJa: "肺炎マイコプラズマ",
      scientificNameEnRubi: "マイコプラズマ・ニューモニエ",  
      scientificNameEn: "<em>Mycoplasma pneumoniae</em>",
      type: "非定型菌",
      taxonomy: {
        phylum: "<em>Mycoplasmatota</em>",
        class: "<em>Mollicutes</em>",
        order: "<em>Mycoplasmatales</em>",
        family: "<em>Mycoplasmataceae</em>",
      },
      bacterialFeatures: "細胞壁を欠くため、βラクタム系抗菌薬は無効。",
      clinicalFeatures: "非定型肺炎の主要原因菌。",
      additionalInfo: "寒冷凝集素反応が診断に用いられる。",
      img: "<img src='img/chara3.png'>",
      lpsn: "<a href='https://lpsn.dsmz.de/species/mycoplasma-pneumoniae' target='_blank'><em>Mycoplasma pneumoniae</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-03.png", feature:"Royal Family", law:[],
      bsl:2,
    },
    {
      id: 4,
      name: "レジオネラ爺や",
      scientificNameJa: "レジオネラ",     
      scientificNameEnRubi: "レジオネラ・ニューモフィラ",  
      scientificNameEn: "<em>Legionella pneumophila</em>",
      type: "非定型菌",
      taxonomy: {
        phylum: "<em>Pseudomonadota</em>",
        class: "<em>Gammaproteobacteria</em>",
        order: "<em>Legionellales</em>",
        family: "<em>Legionellaceae</em>",
      },
      bacterialFeatures: "淡水環境に生息し、好気性。",
      clinicalFeatures: "レジオネラ肺炎（在郷軍人病）の原因菌。",
      additionalInfo: "エアロゾル感染による集団発生が知られる。",
      img: "<img src='img/chara4.png'>",
      lpsn: "<a href='https://lpsn.dsmz.de/species/legionella-pneumophila' target='_blank'><em>Legionella pneumophila</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-04.png", feature:"Water", law:[],
      bsl:2,
    },
    {
      id: 5,
      name: "ダイチョーキン",
      scientificNameJa: "大腸菌",     
      scientificNameEnRubi: "エシェリヒア・コリ",  
      scientificNameEn: "<em>Escherichia coli</em>",
      type: "グラム陰性桿菌",
      taxonomy: {
        phylum: "<em>Pseudomonadota</em>",
        class: "<em>Gammaproteobacteria</em>",
        order: "<em>Enterobacterales</em>",
        family: "<em>Enterobacteriaceae</em>",
      },
      bacterialFeatures: "腸内常在菌だが、病原性株も存在。",
      clinicalFeatures: "尿路感染症、腸管感染症、敗血症の原因となる。",
      additionalInfo: "O157:H7株は腸管出血性大腸菌（EHEC）として知られる。",
      img: "<img src='img/chara5.png'>",
      lpsn: "<a href='https://lpsn.dsmz.de/species/escherichia-coli' target='_blank'><em>Escherichia coli</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-05.png", feature:"Water", law:[],
      bsl:2,
    },{
      id: 6,
      name: "ベロダシ",
      scientificNameJa: "腸管出血性大腸菌" ,     
      scientificNameEnRubi: "エンテロヘモラージック エシェリヒア・コリ",  
      scientificNameEn: "Enterohemorrhagic <em>Escherichia coli</em>",
      type: "グラム陰性桿菌",
      taxonomy: {
          phylum: "<em>Pseudomonadota</em>",
          class: "<em>Gammaproteobacteria</em>",
          order: "<em>Enterobacterales</em>",
          family: "<em>Enterobacteriaceae</em>",
      },
      bacterialFeatures: "志賀毒素（Shiga toxin）を産生する株。",
      clinicalFeatures: "重症例では溶血性尿毒症症候群（HUS）を引き起こす。",
      additionalInfo: "生食による感染が多く、食品衛生上の重要な病原菌。",
      img: "<img src='img/chara6.png'>",
      lpsn: "<a href='https://lpsn.dsmz.de/species/escherichia-coli' target='_blank'><em>Escherichia coli</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-06.png", feature:"Water", law:[],bsl:2,
  },
  {
      id: 7,
      name: "シゲ裸族",
      scientificNameJa: "赤痢菌" ,     
      scientificNameEnRubi: "シゲラ・ディセンテリエ",  
      scientificNameEn: "<em>Shigella dysenteriae</em>",
      type: "グラム陰性桿菌",
      taxonomy: {
          phylum: "<em>Pseudomonadota</em>",
          class: "<em>Gammaproteobacteria</em>",
          order: "<em>Enterobacterales</em>",
          family: "<em>Enterobacteriaceae</em>",
      },
      bacterialFeatures: "少量の細菌でも感染成立する強い病原性。",
      clinicalFeatures: "激しい腹痛、血性下痢を引き起こす。",
      additionalInfo: "感染経路は主に汚染水や食品、接触感染。",
      img: "<img src='img/chara7.png'>",
      lpsn: "<a href='https://lpsn.dsmz.de/species/shigella-dysenteriae' target='_blank'><em>Shigella dysenteriae</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-07.png", feature:"Water", law:[],bsl:2,
  },
  {
      id: 8,
      name: "クレブシエ裸族",
      scientificNameJa: "肺炎桿菌" ,     
      scientificNameEnRubi: "クレブシエラ・ニューモニエ",  
      scientificNameEn: "<em>Klebsiella pneumoniae</em>",
      type: "グラム陰性桿菌",
      taxonomy: {
          phylum: "<em>Pseudomonadota</em>",
          class: "<em>Gammaproteobacteria</em>",
          order: "<em>Enterobacterales</em>",
          family: "<em>Enterobacteriaceae</em>",
      },
      bacterialFeatures: "大腸菌と並ぶ腸内細菌科の代表的な細菌。厚い莢膜を持つ。",
      clinicalFeatures: "市中肺炎や尿路感染症、敗血症の原因となる。",
      additionalInfo: "高病原性肺炎桿菌（hvKP）もしくは高粘稠性肺炎桿菌（hmKP）が近年問題となっている。",
      img: "<img src='img/chara8.png'>",
      lpsn: "<a href='https://lpsn.dsmz.de/species/klebsiella-pneumoniae' target='_blank'><em>Klebsiella pneumoniae</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-08.png", feature:"Water", law:[],bsl:2,
  },
  {
      id: 9,
      name: "ビブリ男コレラ",
      scientificNameJa: "コレラ菌" ,     
      scientificNameEnRubi: "ビブリオ・ヒョレレ",  
      scientificNameEn: "<em>Vibrio cholerae</em>",
      type: "グラム陰性桿菌",
      taxonomy: {
          phylum: "<em>Pseudomonadota</em>",
          class: "<em>Gammaproteobacteria</em>",
          order: "<em>Vibrionales</em>",
          family: "<em>Vibrionaceae</em>",
      },
      bacterialFeatures: "鞭毛を持つ好塩性菌で、コレラ毒素を産生。",
      clinicalFeatures: "重度の水様性下痢を引き起こす（脱水症状が顕著）。",
      additionalInfo: "汚染された水や食品を介して感染する。",
      img: "<img src='img/chara9.png'>",
      lpsn: "<a href='https://lpsn.dsmz.de/species/vibrio-cholerae' target='_blank'><em>Vibrio cholerae</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-09.png", feature:"Water", law:[],bsl:2,
  },
  {
      id: 10,
      name: "リョクノーキン",
      scientificNameJa: "緑膿菌" ,     
      scientificNameEnRubi: "シュードモナス・エルギノーザ",  
      scientificNameEn: "<em>Pseudomonas aeruginosa</em>",
      type: "グラム陰性桿菌",
      taxonomy: {
          phylum: "<em>Pseudomonadota</em>",
          class: "<em>Gammaproteobacteria</em>",
          order: "<em>Pseudomonadales</em>",
          family: "<em>Pseudomonadaceae</em>",
      },
      bacterialFeatures: "好気性で、多剤耐性を示す場合が多い。",
      clinicalFeatures: "易感染性宿主における肺炎や菌血症の原因菌。",
      additionalInfo: "医療関連感染で重要な病原菌。",
      img: "<img src='img/chara10.png'>",
      lpsn: "<a href='https://lpsn.dsmz.de/species/pseudomonas-aeruginosa' target='_blank'><em>Pseudomonas aeruginosa</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-10.png", feature:"Water", law:[],bsl:2,
  },{
    id: 11,
    name: "アシネトバクター",
    scientificNameJa: "アシネトバクター",
    scientificNameEnRubi: "アシネトバクター・バウマニー",  
    scientificNameEn: "<em>Acinetobacter baumannii</em>",
    type: "グラム陰性桿菌",
    taxonomy: {
        phylum: "<em>Pseudomonadota</em>",
        class: "<em>Gammaproteobacteria</em>",
        order: "<em>Pseudomonadales</em>",
        family: "<em>Moraxellaceae</em>",
    },
    bacterialFeatures: "環境中に広く存在し、多剤耐性化が問題視される。",
    clinicalFeatures: "医療関連感染（肺炎、尿路感染症、創感染など）の原因菌。",
    additionalInfo: "耐性遺伝子の水平伝播が確認されており、治療が困難な場合がある。",
    img: "<img src='img/chara11.png'>",
    lpsn: "<a href='https://lpsn.dsmz.de/species/acinetobacter-baumannii' target='_blank'><em>Acinetobacter baumannii</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-11.png", feature:"Water", law:[],bsl:2,
},
{
    id: 12,
    name: "チフス和尚",
    scientificNameJa: "腸チフス菌",
    scientificNameEnRubi: "サルモネラ・ティフィ",
    scientificNameEn: "<em>Salmonella </em>Typhi",
    type: "グラム陰性桿菌",
    taxonomy: {
        phylum: "<em>Pseudomonadota</em>",
        class: "<em>Gammaproteobacteria</em>",
        order: "<em>Enterobacterales</em>",
        family: "<em>Enterobacteriaceae</em>",
    },
    bacterialFeatures: "抗酸性を持たず、腸管内に感染する。",
    clinicalFeatures: "腸チフスを引き起こし、高熱や消化管症状が特徴。",
    additionalInfo: "経口感染が主な感染経路。予防には清潔な水と食品の管理が重要。",
    img: "<img src='img/chara12.png'>",
    lpsn: "<a href='https://lpsn.dsmz.de/species/salmonella-enterica' target='_blank'><em>Salmonella enterica</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-12.png", feature:"Default", law:[],bsl:2,
},
{
    id: 13,
    name: "クラミジア・ニューモニエ侯",
    scientificNameJa: "肺炎クラミジア",
    scientificNameEnRubi: "クラミジア・ニューモニエ",  
    scientificNameEn: "<em>Chlamydia pneumoniae</em>",
    type: "細胞内寄生菌",
    taxonomy: {
        phylum: "<em>Chlamydiota</em>",
        class: "<em>Chlamydiia</em>",
        order: "<em>Chlamydiales</em>",
        family: "<em>Chlamydiaceae</em>",
    },
    bacterialFeatures: "細胞内で増殖し、エネルギー依存性。",
    clinicalFeatures: "気管支炎や肺炎を引き起こす。",
    additionalInfo: "非定型肺炎の原因菌の一つ。PCR検査で診断される。",
    img: "<img src='img/chara13.png'>",
    lpsn: "<a href='https://lpsn.dsmz.de/species/chlamydia-pneumoniae' target='_blank'><em>Chlamydia pneumoniae</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-13.png", feature:"Royal Family", law:[],bsl:2,
},
{
    id: 14,
    name: "クラミジア・シッタ氏",
    scientificNameJa: "オウム病クラミジア",
    scientificNameEnRubi: "クラミジア・シッタシ",  
    scientificNameEn: "<em>Chlamydia psittaci</em>",
    type: "細胞内寄生菌",
    taxonomy: {
        phylum: "<em>Chlamydiota</em>",
        class: "<em>Chlamydiia</em>",
        order: "<em>Chlamydiales</em>",
        family: "<em>Chlamydiaceae</em>",
    },
    bacterialFeatures: "鳥類に感染し、ヒトに伝播する。",
    clinicalFeatures: "オウム病（肺炎、発熱、全身症状）を引き起こす。",
    additionalInfo: "鳥類との接触がリスク要因。PCRや血清学的検査で診断。",
    img: "<img src='img/chara14.png'>",
    lpsn: "<a href='https://lpsn.dsmz.de/species/chlamydia-psittaci' target='_blank'><em>Chlamydia psittaci</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-14.png", feature:"Royal Family", law:[],bsl:2,
},
{
    id: 15,
    name: "ブドーキューキン族（黄色部族）",
    scientificNameJa: "黄色ブドウ球菌",
    scientificNameEnRubi: "スタフィロコックス・アウレウス",  
    scientificNameEn: "<em>Staphylococcus aureus</em>",
    type: "グラム陽性球菌",
    taxonomy: {
        phylum: "<em>Bacillota</em>",
        class: "<em>Bacilli</em>",
        order: "<em>Bacillales</em>",
        family: "<em>Staphylococcaceae</em>",
    },
    bacterialFeatures: "コアグラーゼ陽性で、耐性菌（MRSA）が問題となる。",
    clinicalFeatures: "化膿性感染症や毒素性ショック症候群（TSS）の原因。",
    additionalInfo: "常在菌だが、侵入すると感染を引き起こす。",
    img: "<img src='img/chara15.png'>",
    lpsn: "<a href='https://lpsn.dsmz.de/species/staphylococcus-aureus' target='_blank'><em>Staphylococcus aureus</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-15.png", feature:"Common", law:[],bsl:2,
},{
  id: 16,
  name: "ケッカクキン",
  scientificNameJa: "結核菌",
  scientificNameEnRubi: "マイコバクテリウム・ツベルクローシス",  
  scientificNameEn: "<em>Mycobacterium tuberculosis</em>",
  type: "抗酸菌",
  taxonomy: {
      phylum: "<em>Actinomycetota</em>",
      class: "<em>Actinomycetia</em>",
      order: "<em>Mycobacteriales</em>",
      family: "<em>Mycobacteriaceae</em>",
  },
  bacterialFeatures: "細胞壁にミコール酸を含むため抗酸染色で染色可能。",
  clinicalFeatures: "結核の原因菌で、慢性咳嗽、発熱、体重減少を引き起こす。",
  additionalInfo: "空気感染により伝播。BCGワクチンで予防可能だが、成人結核には効果が限定的。",
  img: "<img src='img/chara16.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/mycobacterium-tuberculosis' target='_blank'><em>Mycobacterium tuberculosis</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-16.png", feature:"Default", law:["結核（2類）","結核菌（特定4種）","多剤耐性結核菌（特定3種）"],bsl:3,
},
{
  id: 17,
  name: "MAC",
  scientificNameJa: "非結核性抗酸菌（MAC）",
  scientificNameEnRubi: "マイコバクテリウム・アイウム・コンプレックス",  
  scientificNameEn: "<em>Mycobacterium avium</em> complex",
  type: "抗酸菌",
  taxonomy: {
      phylum: "<em>Actinomycetota</em>",
      class: "<em>Actinomycetia</em>",
      order: "<em>Mycobacteriales</em>",
      family: "<em>Mycobacteriaceae</em>",
  },
  bacterialFeatures: "結核菌に似た抗酸菌だが、ヒトからヒトへの感染はない。",
  clinicalFeatures: "易感染性宿主における肺MAC症やリンパ節炎の原因。",
  additionalInfo: "自然環境中に広く存在し、主に水や土壌を通じて感染。",
  img: "<img src='img/chara17.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/mycobacterium-avium' target='_blank'><em>Mycobacterium avium</em></a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-17.png", feature:"Default", law:[],bsl:2,
},
{
  id: 18,
  name: "コクシジオイデス海賊王",
  scientificNameJa: "コクシジオイデス",
  scientificNameEnRubi: "コクシジオイデス・イミティス",  
  scientificNameEn: "<em>Coccidioides immitis</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Sordariomycetes</em>",
      order: "<em>Onygenales</em>",
      family: "<em>Onygenaceae</em>",
  },
  bacterialFeatures: "土壌に生息し、胞子を吸入することで感染。",
  clinicalFeatures: "コクシジオイデス症（バレー熱）を引き起こす。",
  additionalInfo: "アメリカ南西部など乾燥地域で多く発生。",
  img: "<img src='img/chara18.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/coccidioides-immitis' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-18.png", feature:"Hot", law:[],bsl:3,
},
{
  id: 19,
  name: "ヒストプラズ魔王",
  scientificNameJa: "ヒストプラズマ",
  scientificNameEnRubi: "ヒストプラズマ・カプスラーツム",  
  scientificNameEn: "<em>Histoplasma capsulatum</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Eurotiomycetes</em>",
      order: "<em>Onygenales</em>",
      family: "<em>Ajellomycetaceae</em>",
  },
  bacterialFeatures: "土壌や鳥の糞に存在し、胞子を吸入して感染。",
  clinicalFeatures: "ヒストプラズマ症（肺炎や全身感染）を引き起こす。",
  additionalInfo: "免疫不全患者では重症化する。",
  img: "<img src='img/chara19.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/histoplasma-capsulatum' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-197.png", feature:"Hot", law:[],bsl:3,
},
{
  id: 20,
  name: "パラコクシジオイデス",
  scientificNameJa: "パラコクシジオイデス",
  scientificNameEnRubi: "パラコクシジオイデス・ブラジリエンシス",  
  scientificNameEn: "<em>Paracoccidioides brasiliensis</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Eurotiomycetes</em>",
      order: "<em>Onygenales</em>",
      family: "<em>Ajellomycetaceae</em>",
  },
  bacterialFeatures: "南米に多い真菌で、土壌に存在。",
  clinicalFeatures: "パラコクシジオイデス症（慢性肉芽腫性疾患）を引き起こす。",
  additionalInfo: "肺から全身に感染が広がることがある。",
  img: "<img src='img/chara20.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/paracoccidioides-brasiliensis' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-20.png", feature:"Hot", law:[],bsl:3,
},
{
  id: 21,
  name: "ミセス・ブラスト",
  scientificNameJa: "ブラストミセス",
  scientificNameEnRubi: "ブラストミセス・デルマティティディス",  
  scientificNameEn: "<em>Blastomyces dermatitidis</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Eurotiomycetes</em>",
      order: "<em>Onygenales</em>",
      family: "<em>Ajellomycetaceae</em>",
  },
  bacterialFeatures: "環境中の胞子を吸入して感染。",
  clinicalFeatures: "皮膚や肺に感染するブラストミセス症を引き起こす。",
  additionalInfo: "北米で主に発生。免疫低下者で重症化しやすい。",
  img: "<img src='img/chara21.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/blastomyces-dermatitidis' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-21.png", feature:"Hot", law:[],bsl:3,
},
{
  id: 22,
  name: "タラロマイセス・マルネッフェイ",
  scientificNameJa: "タラロマイセス・マルネッフェイ",
  scientificNameEnRubi: "タラロマイセス・マルネッフェイ",  
  scientificNameEn: "<em>Talaromyces marneffei</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Eurotiomycetes</em>",
      order: "<em>Eurotiales</em>",
      family: "<em>Trichocomaceae</em>",
  },
  bacterialFeatures: "熱帯地域に多い真菌で、二形性を持つ。",
  clinicalFeatures: "免疫低下者で肺感染や全身感染を引き起こす。",
  additionalInfo: "HIV患者で特に重症化する傾向がある。",
  img: "<img src='img/chara22.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/talaromyces-marneffei' target='_blank'>LPSN</a>",
  card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-22.png", feature:"Hot", law:[],bsl:3,
},
{
  id: 23,
  name: "クリプトコックス・ネオフォルマンス",
  scientificNameJa: "クリプトコックス・ネオフォルマンス",
  scientificNameEnRubi: "クリプトコックス・ネオフォルマンス",  
  scientificNameEn: "<em>Cryptococcus neoformans</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Basidiomycota</em>",
      class: "<em>Tremellomycetes</em>",
      order: "<em>Tremellales</em>",
      family: "<em>Tremellaceae</em>",
  },
  bacterialFeatures: "莢膜を持つ真菌で、鳥の糞中に存在。",
  clinicalFeatures: "クリプトコックス症（特に髄膜炎）を引き起こす。",
  additionalInfo: "免疫不全患者で重症化しやすい。",
  img: "<img src='img/chara23.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/cryptococcus-neoformans' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-23.png", feature:"Default", law:[],bsl:2,
},
{
  id: 24,
  name: "クリプトコックス・ガッティ",
  scientificNameJa: "クリプトコックス・ガッティ",
  scientificNameEnRubi: "クリプトコックス・ガッティ",  
  scientificNameEn: "<em>Cryptococcus gattii</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Basidiomycota</em>",
      class: "<em>Tremellomycetes</em>",
      order: "<em>Tremellales</em>",
      family: "<em>Tremellaceae</em>",
  },
  bacterialFeatures: "熱帯地域に多く、莢膜を持つ。",
  clinicalFeatures: "肺や中枢神経系に感染するクリプトコックス症を引き起こす。",
  additionalInfo: "健常者でも感染することがある。",
  img: "<img src='img/chara24.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/cryptococcus-gattii' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-24.png", feature:"Default", law:[],bsl:2,
},
{
  id: 25,
  name: "カンジダ",
  scientificNameJa: "カンジダ・アルビカンス",
  scientificNameEnRubi: "カンジダ・アルビカンス",  
  scientificNameEn: "<em>Candida albicans</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Saccharomycetes</em>",
      order: "<em>Saccharomycetales</em>",
      family: "<em>Saccharomycetaceae</em>",
  },
  bacterialFeatures: "常在真菌だが、免疫低下時に病原性を示す。",
  clinicalFeatures: "口腔カンジダ症やカンジダ血症を引き起こす。",
  additionalInfo: "抗真菌薬による治療が可能。",
  img: "<img src='img/chara25.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/candida-albicans' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-25.png", feature:"Default", law:[],bsl:2,
},{
  id: 26,
  name: "アスペルギルス",
  scientificNameJa: "アスペルギルス フミガツス",
  scientificNameEnRubi: "アスペルギルス・フミガツス",  
  scientificNameEn: "<em>Aspergillus fumigatus</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Eurotiomycetes</em>",
      order: "<em>Eurotiales</em>",
      family: "<em>Trichocomaceae</em>",
  },
  bacterialFeatures: "胞子が空気中に浮遊し、吸入することで感染。",
  clinicalFeatures: "アスペルギルス症（アレルギー性肺疾患や侵襲性肺感染症）を引き起こす。",
  additionalInfo: "免疫不全患者において致命的になる場合がある。",
  img: "<img src='img/chara26.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/aspergillus-fumigatus' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-26.png", feature:"Default", law:[],bsl:2,
},
{
  id: 27,
  name: "コーボくん",
  scientificNameJa: "酵母菌",
  scientificNameEnRubi: "サッカロマイセス・セレビジエ",  
  scientificNameEn: "<em>Saccharomyces cerevisiae</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Saccharomycetes</em>",
      order: "<em>Saccharomycetales</em>",
      family: "<em>Saccharomycetaceae</em>",
  },
  bacterialFeatures: "エタノール発酵を行うことで知られる。",
  clinicalFeatures: "通常は非病原性だが、稀に免疫不全患者で感染症を引き起こす。",
  additionalInfo: "パンやアルコールの発酵に利用される重要な微生物。",
  img: "<img src='img/chara27.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/saccharomyces-cerevisiae' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-27.png", feature:"Default", law:[],bsl:1,
},
{
  id: 28,
  name: "こうじ君",
  scientificNameJa: "麹菌",
  scientificNameEnRubi: "アスペルギルス・オリゼ",  
  scientificNameEn: "<em>Aspergillus oryzae</em>",
  type: "真菌",
  taxonomy: {
      phylum: "<em>Ascomycota</em>",
      class: "<em>Eurotiomycetes</em>",
      order: "<em>Eurotiales</em>",
      family: "<em>Trichocomaceae</em>",
  },
  bacterialFeatures: "デンプンを分解して糖を生成する酵素を生産。",
  clinicalFeatures: "非病原性。食品発酵に利用される。",
  additionalInfo: "日本の伝統的な食品（味噌、醤油、清酒）の製造に欠かせない。",
  img: "<img src='img/chara28.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/aspergillus-oryzae' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-28.png", feature:"Default", law:[],bsl:1,
},
{
  id: 29,
  name: "A軍連隊",
  scientificNameJa: "溶血性レンサ球菌（A群）",
  scientificNameEnRubi: "ストレプトコックス・ピオジェネス",  
  scientificNameEn: "<em>Streptococcus pyogenes</em>",
  type: "グラム陽性球菌",
  taxonomy: {
      phylum: "<em>Bacillota</em>",
      class: "<em>Bacilli</em>",
      order: "<em>Lactobacillales</em>",
      family: "<em>Streptococcaceae</em>",
  },
  bacterialFeatures: "β溶血性を示し、化膿性病変を引き起こす。",
  clinicalFeatures: "咽頭炎、猩紅熱、リウマチ熱の原因菌。",
  additionalInfo: "ペニシリン系抗菌薬が有効。",
  img: "<img src='img/chara29.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/streptococcus-pyogenes' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-29.png", feature:"Default", law:[],bsl:2,
},
{
  id: 30,
  name: "B軍連隊",
  scientificNameJa: "溶血性レンサ球菌（B群）",
  scientificNameEnRubi: "ストレプトコックス・アガラクティエ",  
  scientificNameEn: "<em>Streptococcus agalactiae</em>",
  type: "グラム陽性球菌",
  taxonomy: {
      phylum: "<em>Bacillota</em>",
      class: "<em>Bacilli</em>",
      order: "<em>Lactobacillales</em>",
      family: "<em>Streptococcaceae</em>",
  },
  bacterialFeatures: "腸管や膣に常在するが、新生児感染のリスクがある。",
  clinicalFeatures: "新生児髄膜炎、敗血症の原因。",
  additionalInfo: "妊婦スクリーニングが重要。",
  img: "<img src='img/chara30.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/streptococcus-agalactiae' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-30.png", feature:"Default", law:[],bsl:2,
},
{
  id: 31,
  name: "ディフィシル",
  scientificNameJa: "ディフィシル菌",
  scientificNameEnRubi: "クロストリジオイデス・ディフィシル",  
  scientificNameEn: "<em>Clostridioides difficile</em>",
  type: "グラム陽性嫌気性桿菌",
  taxonomy: {
      phylum: "<em>Bacillota</em>",
      class: "<em>Clostridia</em>",
      order: "<em>Clostridiales</em>",
      family: "<em>Clostridiaceae</em>",
  },
  bacterialFeatures: "毒素AおよびBを産生し、抗菌薬関連下痢症の原因となる。",
  clinicalFeatures: "偽膜性大腸炎を引き起こす。",
  additionalInfo: "糞便移植療法が有効な場合がある。",
  img: "<img src='img/chara31.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/clostridioides-difficile' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-31.png", feature:"Default", law:[],bsl:2,
},
{
  id: 32,
  name: "タンソ",
  scientificNameJa: "炭疽菌",
  scientificNameEnRubi: "バチルス・アントラチス",  
  scientificNameEn: "<em>Bacillus anthracis</em>",
  type: "グラム陽性芽胞形成桿菌",
  taxonomy: {
      phylum: "<em>Bacillota</em>",
      class: "<em>Bacilli</em>",
      order: "<em>Bacillales</em>",
      family: "<em>Bacillaceae</em>",
  },
  bacterialFeatures: "芽胞を形成し、長期間環境中で生存可能。",
  clinicalFeatures: "炭疽（皮膚炭疽、肺炭疽など）を引き起こす。",
  additionalInfo: "バイオテロリズムのリスクがある病原体。",
  img: "<img src='img/chara32.png'>",
  lpsn: "<a href='https://lpsn.dsmz.de/species/bacillus-anthracis' target='_blank'>LPSN</a>",quiztag:[], card:"https://www.omu.ac.jp/med/bacteriology/online/image/card/img-card-32.png", feature:"Default", law:["炭疽（2類）","炭疽菌（特定2種）"],bsl:3,
},
  ];
  